openapi: 3.0.3
info:
  title: Task App REST API
  version: '1.0.0'
  description: Task App for Educational Purpose
tags:
  - name: task
    description: タスクに関するAPI
  - name: user
    description: ユーザに関するAPI
servers:
  - url: 'http://localhost:8080/api'
paths:
  /tasks:
    get:
      summary: タスク一覧の取得
      tags:
        - task
      description: >
        登録しているタスクをすべて取得する
      operationId: getTasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTasksResponse'
              examples:
                example1:
                  value:
                    - tasks:
                        - id: 1
                          title: 牛乳を買う
                          completed: false
                        - id: 2
                          title: 手紙を出す
                          completed: false
    post:
      summary: タスクの登録
      tags:
        - task
      description: >
        タスクを登録する
      operationId: postTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
            examples:
              example1:
                value:
                  title: プログラミングを勉強する
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                example1:
                  value:
                    id: 3
                    title: プログラミングを勉強する
                    completed: false
        "400":
          description: Bad Request
        "403":
          description: Forbidden
  /tasks/{taskId}:
    parameters:
      - name: taskId
        in: path
        description: タスクID
        required: true
        schema:
          type: number
        example: 3
    put:
      summary: タスクステータスの更新
      description: >
        タスクのステータスを更新する。
      tags:
        - task
      operationId: putTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: タスクのステータス
              required:
                - completed
              additionalProperties: false
            examples:
              example1:
                value:
                  completed: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                example1:
                  value:
                    id: 3
                    title: プログラミングを勉強する
                    completed: true
        "400":
          description: Bad Request
    delete:
      summary: タスクの削除
      description: >
        登録しているタスクを削除する。
      tags:
        - task
      operationId: deleteTask
      responses:
        '204':
          description: No Content
  /login:
    post:
      summary: ログイン
      description: >
        ユーザ情報で認証を行い、認証に成功した場合はログインする
      tags:
        - user
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            examples:
              example1:
                value:
                  username: tanaka
                  password: 12345
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
components:
  schemas:
    Task:
      type: object
      description: タスク情報
      properties:
        id:
          type: integer
          description: タスクのID
        title:
          type: string
          description: タスクのタイトル
        completed:
          type: boolean
          description: タスクのステータス
      required:
        - id
        - title
        - completed
      additionalProperties: false
    GetTasksResponse:
      type: object
      description: タスク一覧の取得レスポンス
      properties:
        tasks:
          type: array
          description: タスク一覧
          items:
            $ref: '#/components/schemas/Task'
    LoginRequest:
      type: object
      description: ログインリクエスト
      properties:
        username:
          type: string
          description: ユーザ名
        password:
          type: string
          description: パスワード
      additionalProperties: false
