version: "3.9"

services:
  mysql:
    image: mysql:8.4.4
    platform: linux/amd64
    container_name: taskapp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskapp
      TZ: "Asia/Tokyo"
